### ISSUE TITLE
Improperly specified VM option: MaxPermSize

### ISSUE THREAD

**Issue by brdloush** [snasello/docker-liferay-6.2#1]
The container doesn't start for me:

docker@boot2docker:~$ docker run --rm -t -i -p 8080:8080 snasello/liferay-6.2:6.2-ce-ga2
Using CATALINA_BASE:   /opt/liferay-portal-6.2-ce-ga2/tomcat-7.0.42
Using CATALINA_HOME:   /opt/liferay-portal-6.2-ce-ga2/tomcat-7.0.42
Using CATALINA_TMPDIR: /opt/liferay-portal-6.2-ce-ga2/tomcat-7.0.42/temp
Using JRE_HOME:        /opt/java
Using CLASSPATH:       /opt/liferay-portal-6.2-ce-ga2/tomcat-7.0.42/bin/bootstrap.jar:/opt/liferay-portal-6.2-ce-ga2/tomcat-7.0.42/bin/tomcat-juli.jar
Improperly specified VM option 'MaxPermSize=256m-e'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

docker@boot2docker:~$ date
Sat Oct 25 08:29:01 UTC 2014
docker@boot2docker:~$ docker images
REPOSITORY               TAG                   IMAGE ID            CREATED             VIRTUAL SIZE
snasello/liferay-6.2     6.2-ce-ga2            62cbd16b7d07        2 days ago          663.9 MB

**Comment by dunnleaddress** [comment]
error message:
Improperly specified VM option 'MaxPermSize=256m-e'

solution:
You need to properly specified VM option 'MaxPermSize=256m' (without -e)

**Comment by HEWU10** [comment]
i think so .
